permissions:
  actions: read

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Begin getting telemetry
        id: shame
        uses: uptick/actions-collect-otel@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # TODO: Configure fetch-depth?
          fetch-depth: 2
